### PR TITLE
Stop using the docker container

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Review by varungandhi-src — APPROVED** [review]

**Comment by varungandhi-src** [comment]
I think this is OK, but it uses an extra file for pinning the node version. So if someone is looking at this repo as an example, they need to look at 2 files instead of 1, and we need to make sure that the reader is aware of that.

**Comment by olafurpg** [comment]
lsif-typescript should actually be compatible with fairly old node versions. We should probably test this in CI, I already refactored some code to remove usage of new Node features because the autoindexing image used Node 13.

**Comment by olafurpg** [comment]
The more Node versions we're compatible with the easier it will be to integrate lsif-typescript at different companies

**Comment by varungandhi-src** [comment]
> We should probably test this in CI, I already refactored some code to remove usage of new Node features because the autoindexing image used Node 13.

Hmm, I don't think we're compatible with such old Node versions. That's why I bumped the Node version in the Docker image. https://github.com/sourcegraph/lsif-typescript/pull/103

**Pull request merged**
