### PR TITLE
Test and fix workflow

### PR DESCRIPTION
**Pull request by varungandhi-src**
It looks like this is broken for some inexplicable reason that doesn't reproduce locally. https://github.com/sourcegraph-codeintel-showcase/lodash/actions/runs/2243923689

### CODE REVIEW

**Comment by varungandhi-src** [comment]
The problem seems to be specific to the Docker image... 😮‍💨 I am able to reproduce locally with that image hash. `4bb2f29841b5bc46b82f038671ce08d57470d917973151a843fa267386de5ac6`

**Review by olafurpg — COMMENTED** [review]
Where does that sha come from? I'm unable to reproduce with the latest `:autoindex` tag 🤔 
```
❯ docker run -v $(pwd):/node -it sourcegraph/lsif-typescript:autoindex /bin/bash
bash-5.1# cd /node
bash-5.1# lsif-typescript index --infer-tsconfig
+ /node (4.6s)
done /node/dump.lsif-typed
```

**Comment by olafurpg** [comment]
I opened #4 to remove the usage of the docker container. I think it's best to not rely on Docker for usage examples since the raw installation steps are easier to port into any CI system (or other custom Docker containers)

**Comment by varungandhi-src** [comment]
Will there automatically be an engine version check? One concern with removing the Docker container is that someone may be using a very old version of Node.

The SHA was based on the latest tag, not the autoindex tag.

**Pull request closed without merging**
